all:
	cd Q1 && make && cd .. 
	cd Q2 && make && cd .. 
	cd Q3 && make && cd ..
	
test:
	cd Q1 && echo "\nTesting Q1 ...\n____________\n" && ./p1q1 && cd .. 
	cd Q2 && echo "\nTesting Q2 ...\n____________\n" && ./p1q2 && cd .. 
	cd Q3 && echo "\nTesting Q3 ...\n____________\n" && ./p1q3 && cd ..

clean: 
	cd Q1 && make clean && cd .. 
	cd Q2 && make clean && cd .. 
	cd Q3 && make clean && cd ..
	
